version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'