apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-cronjob
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: arcadial/resume-matcher-scraper:k8s
          restartPolicy: OnFailure
